name: Test Action

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the action
      uses: ./
      with:
        packages: latex-bin
        cache_version: ${{ github.run_id }}_${{ github.run_attempt }}
    - run: pdflatex test.tex

  run-with-cache:
    needs: first-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the action
      uses: ./
      with:
        packages: latex-bin
        cache_version: ${{ github.run_id }}_${{ github.run_attempt }}
        repository: https://127.0.0.42/not-a-texlive-mirror/
    - run: pdflatex test.tex

  run-without-cache:
    needs: first-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the action
      uses: ./
      with:
        packages: latex-bin blindtext
        cache_version: ${{ github.run_id }}_${{ github.run_attempt }}
    - run: pdflatex test-blindtext.tex
