name: Test Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run the action
      uses: ./
    - run: pdflatex test.tex

  testcache:
    needs: text
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run the action
      uses: ./
    - run: pdflatex test.tex
