name: Test Action

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run the action
      uses: ./
    - run: pdflatex test.tex

  testcache:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run the action
      uses: ./
    - run: echo $PATH
    - run: ls -la $HOME/texlive/bin/x86_64-linux/pdflatex
    - run: pdflatex test.tex
